### ISSUE TITLE
Getting error after install

### ISSUE THREAD

**Issue by bj-mcduck** [recurser/pivotal-to-trello#4]
I get `zsh: command not found: pivotal-to-trello` when running the `pivotal-to-trello` command after installing. Probably a `zsh` thing-ish. But my regular fix of prepending `noglob` for it didn't work.

Possibly need to locate the gem, find the executable file and call it manually.

**Comment by recurser** [comment]
Hi @brandonjmckay, yes this does seem like it is probably a shell-related path thing. Closing, but feel free to re-open it if you can't figure it out.
