### ISSUE TITLE
Import failing - Trello and PT using conflicting rest-client versions

### ISSUE THREAD

**Issue by spreston01** [recurser/pivotal-to-trello#5]
When I try to run the pivotal to trello import I get the following error:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate pivotal-tracker-0.5.12, because rest-client-1.7.2 conflicts with rest-client (~> 1.6.0), rest-client (~> 1.6.0) (Gem::LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in`activate'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1212:in `block in activate_dependencies'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in`each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in`activate'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
    from /usr/bin/pivotal-to-trello:22:in`<main>'

**Comment by vmueller71** [comment]
I'm having the exact same error.
Any solution yet?

**Comment by vmueller71** [comment]
Figured it out actually.
The problem stems form the ruby-trello gem.
You have to uninstall the latest version and install 1.1.1 instead, then it works.

**Comment by recurser** [comment]
Thanks for the report @spreston01, and apologies for the delay. I've just pushed [version 0.2.0](https://rubygems.org/gems/pivotal-to-trello/versions/0.2.0) which should fix this.
