### ISSUE TITLE
everything going to a single Trello list

### ISSUE THREAD

**Issue by zevaverbach** [recurser/pivotal-to-trello#8]
This happens regardless of where it's directed to go.

**Comment by recurser** [comment]
Hi @zevaverbach, are you still having problems with this? I know it has been years :) The [0.2.0 release](https://rubygems.org/gems/pivotal-to-trello/versions/0.2.0) release has a bunch of fixes which may help here. Closing, but feel free to re-open if you're still having issues.

**Comment by zevaverbach** [comment]
Dave, I don't use Pivotal anymore, so it's not super easy for me to test.
Thanks for addressing some of these issues, though!

Zev Averbach
Averbach Transcription
(802) 276-5934
avtranscription.com <http://www.avtranscription.com/>

**Comment by recurser** [comment]
@zevaverbach no probs, thanks for reporting it!
